### ISSUE TITLE
Check of followings Twitter

### ISSUE THREAD

**Issue by Suriv** [jabrena/microAppsOnDemand#1]
Chequear dos o tres seguidores de una lista de usuario por csv.

La salida, en una lista donde se muestra el usuario, la salida y el comentario:

KO - no sigue a ninguno  / de los seguidores propuestos
KO - no sigue a XXXX  / alguno de los seguidores
REP - Usuario Repetido
OK
Rev - Revisión si su cuenta esta protegida.

Realización PHP

**Comment by jabrena** [comment]
Para la conexión a Twitter, se empleara este desarrollo:
https://github.com/J7mbo/twitter-api-php

**Comment by jabrena** [comment]
http://iag.me/socialmedia/build-your-first-twitter-app-using-php-in-8-easy-steps/
http://iag.me/socialmedia/how-to-create-a-twitter-app-in-8-easy-steps/

**Comment by jabrena** [comment]
Autenticación en Twitter.
https://github.com/abraham/twitteroauth

**Comment by jabrena** [comment]
Demo to connect with TwitterAPI: Success:

**Comment by jabrena** [comment]
Lectura de CVS: Sucess

**Comment by jabrena** [comment]
Get friends count: Ok
Get friends by user: Ok

**Comment by jabrena** [comment]
Para detectar el enlace entre 2 nodos, la via más rapida es emplear este metodo:

https://dev.twitter.com/rest/reference/get/friendships/show

array(1) { ["relationship"]=> array(2) { ["source"]=> array(15) { ["id"]=> int(62625508) ["id_str"]=> string(8) "62625508" ["screen_name"]=> string(13) "juanantoniobm" ["following"]=> bool(true) ["followed_by"]=> bool(true) ["following_received"]=> bool(false) ["following_requested"]=> bool(false) ["notifications_enabled"]=> bool(false) ["can_dm"]=> bool(true) ["blocking"]=> bool(false) ["blocked_by"]=> bool(false) ["muting"]=> bool(false) ["want_retweets"]=> bool(true) ["all_replies"]=> bool(false) ["marked_spam"]=> bool(false) } ["target"]=> array(7) { ["id"]=> int(18882989) ["id_str"]=> string(8) "18882989" ["screen_name"]=> string(6) "isuriv" ["following"]=> bool(true) ["followed_by"]=> bool(true) ["following_received"]=> bool(false) ["following_requested"]=> bool(false) } } }

**Comment by jabrena** [comment]
Fixed.
