### ISSUE TITLE
Develop a JS Client to interoperate with REST API

### ISSUE THREAD

**Issue by jabrena** [jabrena/microAppsOnDemand#5]
It is necessary to create a HTML5 document to make Ajax query every minute.
REST API interoperate with Twitter API and this provider has a rate limit.

**Comment by Suriv** [comment]
http://www.dummies.com/how-to/content/how-to-make-an-ajax-request-with-jquery-for-html5-.html
http://www.keyboardninja.eu/webdevelopment/jquery-ajax-call-tutorial

**Comment by jabrena** [comment]
Ready.
