### ISSUE TITLE
No function localhost

### ISSUE THREAD

**Issue by Suriv** [jabrena/microAppsOnDemand#6]
PHP --version
PHP 5.4.30

Fail in localhost

"( ! ) Notice: Undefined variable: ACCESS_TOKEN in /Users/sortiz/Sites/microAppsOnDemand/twitter1/index.php on line 8
Call Stack
# Time    Memory  Function    Location

1   0.0002  253128  {main}( )   ../index.php:0

( ! ) Notice: Undefined variable: ACCESS_TOKEN_SECRET in /Users/sortiz/Sites/microAppsOnDemand/twitter1/index.php on line 9
Call Stack
# Time    Memory  Function    Location

1   0.0002  253128  {main}( )   ../index.php:0

( ! ) Notice: Undefined variable: CONSUMER_KEY in /Users/sortiz/Sites/microAppsOnDemand/twitter1/index.php on line 10
Call Stack
# Time    Memory  Function    Location

1   0.0002  253128  {main}( )   ../index.php:0

( ! ) Notice: Undefined variable: CONSUMER_SECRET in /Users/sortiz/Sites/microAppsOnDemand/twitter1/index.php on line 12
Call Stack
# Time    Memory  Function    Location

1   0.0002  253128  {main}( )   ../index.php:0

( ! ) Fatal error: Class 'TwitterAPIExchange' not found in /Users/sortiz/Sites/microAppsOnDemand/twitter1/index.php on line 20
Call Stack
# Time    Memory  Function    Location

1   0.0002  253128  {main}( )   ../index.php:0
2   0.0005  254232  showRateLimit( )    ../index.php:29"

**Comment by jabrena** [comment]
It is not a issue.
This service doesn't run in localhost.
The user has to deploy the app in a domain and create their keys to run the application.
https://apps.twitter.com/
